---
swagger: "2.0"
info:
  description: "This is a server for the Nisum Job Board"
  version: "1.0.0"
  title: "Nisum Jobs"
host: "localhost:9090"
basePath: "/"
tags:
- name: "default"
  description: "All job listings"
paths:
  /jobs:
    get:
      operationId: "getAllListings"
      parameters: []
      responses:
        200:
          description: "successful operation"
      x-swagger-router-controller: "Default"
    post:
      summary: "Add a new job listing"
      description: ""
      operationId: "newListing"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Listing object that needs to be added to the store"
        required: false
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Default"
  /jobs/{id}:
    get:
      summary: "Get job by ID"
      description: "Returns a single job"
      operationId: "getListingById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Listing not found"
      x-swagger-router-controller: "Default"
definitions:
  JobListing:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
        example: "John"
      lastName:
        type: "string"
        example: "Doe"
      email:
        type: "string"
        example: "test@test.com"
      phone:
        type: "string"
        example: "(999) 999-9000"
      title:
        type: "string"
      description:
        type: "string"
      qualifications:
        type: "string"
      salary:
        type: "integer"
      jobType:
        type: "string"
      apply:
        type: "string"
      location:
        type: "string"
  body:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
        example: "John"
      lastName:
        type: "string"
        example: "Doe"
      email:
        type: "string"
        example: "test@test.com"
      phone:
        type: "string"
        example: "(999) 999-9000"
      title:
        type: "string"
      description:
        type: "string"
      qualifications:
        type: "string"
      salary:
        type: "integer"
      jobType:
        type: "string"
      apply:
        type: "string"
      location:
        type: "string"
  inline_response_200:
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
        example: "John"
      lastName:
        type: "string"
        example: "Doe"
      email:
        type: "string"
        example: "test@test.com"
      phone:
        type: "string"
        example: "(999) 999-9000"
      title:
        type: "string"
      description:
        type: "string"
      qualifications:
        type: "string"
      salary:
        type: "integer"
      jobType:
        type: "string"
      apply:
        type: "string"
      location:
        type: "string"
